name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4

      - name: Setup docker buildx
      - uses: docker/setup-buildx-action@v3

      - name: Build and run tests in container
        run:
          docker build --target test -t llmserving:test .
      
      - name: Build production image
        if: success()
        run:
          docker build --target production -t llmserving:prod .